# Generated by Django 3.0.2 on 2020-01-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('date_Filed', models.DateTimeField(auto_now=True, verbose_name='dateFiled')),
                ('description', models.CharField(max_length=300)),
                ('filed_By', models.CharField(max_length=50)),
                ('assigned_To', models.CharField(max_length=50)),
                ('completed_by', models.CharField(max_length=50)),
                ('status', models.CharField(default='NEW', max_length=11)),
            ],
        ),
    ]
