# Generated by Django 3.0.2 on 2020-01-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugsBugsBugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('INPROGRESS', 'In Progress'), ('DONE', 'Done'), ('INVALID', 'Invalid')], default='NEW', max_length=11),
        ),
    ]
